name: flutter_paypal
description: A simple but powerful Paypal SDK for flutter.
version: 1.0.0
homepage: https://github.com/Mixpeal/flutter_paypal

environment:
  sdk: ^3.7.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_spinkit: ^5.2.1
  http: ^1.3.0
  http_auth: ^1.0.4
  webview_flutter: ^4.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - lib/src/assets/img/

  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
